/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bookup;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test public void test() {
    	assert 1==2;
    }
}
